version: "3.8"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "notes"
    ports:
      - "3307:3306"
   
  db_admin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1  # Correct the typo in PMA_ARBITRARY
    ports:
      - "8080:80"  # Correct the format of the ports definition

  backend:
    image: node:16
    depends_on:
      - db
    build:
      context: .
    command: >
      bash -c "cd /usr/src/app && npm install && npm start"
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/package.json:/usr/src/app/package.json
      - ./backend/package-lock.json:/usr/src/app/package-lock.json
    ports:
      - "3000:3000"  # Correct the format of the ports definition
    environment:
      HOST_NAME: "db"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
      DB_NAME: "notes"

  nginx:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "3001:80"  # Correct the format of the ports definition
    depends_on:
      - backend
